version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-iot-receiver"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ei4b2mzuuico"
s3_prefix = "aws-iot-receiver"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["IotAtlasMiscFunction=050210506452.dkr.ecr.us-west-2.amazonaws.com/awsiotreceiver41130b41/iotatlasmiscfunction15714fa4repo", "IotAtlasHumiditySplitterFunction=050210506452.dkr.ecr.us-west-2.amazonaws.com/awsiotreceiver41130b41/iotatlashumiditysplitterfunction0ba12d13repo"]
